"""Writes videos/ya-001-ccm/README.md from the real render data (timing + ffprobe/loudness results)."""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
def load(p):
    return json.loads((ROOT / p).read_text())

def shot_table(fmt):
    tm = load(f'build/timing_{fmt}.json')
    rows = ['| # | Shot | Hebrew text (line 1 \\| line 2) | Words | Formula s | Beats | Hold s | In → out (s) | Layer · ALT |',
            '|---|------|------|------|------|------|------|------|------|']
    for i, s in enumerate(tm['shots'], 1):
        txt = s['l1'] + (f" \\| {s['l2']}" if s['l2'] else '')
        rows.append(f"| {i} | {s['key']} | {txt} | {s['words']} | {s['formula']:.2f} | {s['beats']} | {s['hold']:.3f} | "
                    f"{s['start']:.3f} → {s['end']:.3f} | {s['layer']} · {s['alt']:,} FT |")
    tot = (f"**Totals {fmt}:** holds {tm['holdBeats']} beats + {tm['transitions']} transitions × 1 beat = {tm['totalBeats']} beats = "
           f"**{tm['duration']:.3f} s · {tm['frames']} frames · {len(tm['shots'])} shots · {tm['bpm']} BPM** · final hit at {tm['finalHit']:.3f} s")
    return '\n'.join(rows) + '\n\n' + tot

def final_table():
    rows = ['| File | Resolution | fps | Frames | Duration | Video | Audio | Loudness | True peak | Size |', '|---|---|---|---|---|---|---|---|---|---|']
    for fmt in 'AB':
        f = load(f'qa/final_{fmt}.json')
        for k in ('final', 'preview'):
            r = f[k]
            rows.append(f"| `{r['file']}` | {r['width']}×{r['height']} | {r['fps']} | {r['frames']} | {r['duration']:.3f} s | {r['video']} | {r['audio']} | "
                        f"{r['lufs']} LUFS | {r['true_peak_dbfs']} dBTP | {r['size_mb']} MB |")
    return '\n'.join(rows)

ra, rb = load('build/render_A.json'), load('build/render_B.json')
stats = load('src/gen/stats.json')
qa = {f: load(f'qa/{f}/qa.json') for f in 'AB'}

md = f"""# YA-001 · CCM — Claude Code בענן, מהטלפון, לסרטוני מושן בעברית

A no-voiceover Hebrew motion-graphics video about using **Claude Opus 5.5 through Claude Code, even from a phone, in a cloud environment** to make Hebrew motion-graphics videos.
It was produced the same way it describes: a Claude Code cloud session running Opus 5.5 built the page, rendered it, checked its own stills and re-rendered.
The exact production prompt is in [`PROMPT.md`](PROMPT.md).

## Deliverables

{final_table()}

- QA contact sheets: [`qa/contact_A.png`](qa/contact_A.png), [`qa/contact_B.png`](qa/contact_B.png), plus `qa/*/qa.json` (per-shot still times, fonts actually used). The full-size per-shot stills are regenerated by `node src/qa.mjs --fmt A|B` and are not committed, to keep the repo light. Automated QA result: A {len(qa['A']['issues'])} issues, B {len(qa['B']['issues'])} issues (`qa/*/qa.json`).
- Proof shot (16:9 shot 15) values, measured, not pre-written: {stats['shots']} shots · {stats['frames']} frames · {stats['duration']} s · {stats['workers']} render workers ({stats['source']}).
- Render time: 16:9 {ra['seconds']:.0f} s, 9:16 {rb['seconds']:.0f} s on {ra['workers']} workers (4 vCPU cloud VM).

## Shot list A — 16:9 (real holds)

{shot_table('A')}

## Shot list B — 9:16 Reels cut (real holds)

Cut to fit 60 s: WPT 2 and WPT 3 merged, NOTAM 2, NOTAM 3 and PROOF dropped.

{shot_table('B')}

## Facts on screen, and where they're checked

Every product claim was checked against an official page before rendering. All 8 were confirmed, so no on-screen line had to change.

| # | Claim | Source |
|---|---|---|
| 1 | Cloud sessions from the browser at claude.ai/code and from the **Code** tab in the Claude app (iOS/Android) | [Use Claude Code in the cloud](https://code.claude.com/docs/en/claude-code-on-the-web) · [Claude Code on mobile](https://code.claude.com/docs/en/mobile) |
| 2 | GitHub is connected by authorizing the Claude GitHub App (or `/web-setup`) | [Use Claude Code in the cloud — GitHub authentication options](https://code.claude.com/docs/en/claude-code-on-the-web) |
| 3 | Environments have **Network access**, **Environment variables** and a **Setup script** | [Cloud environments](https://code.claude.com/docs/en/cloud-environments) |
| 4 | Opus 5.5, full model name `claude-opus-5-5`; `/model` works in cloud sessions | [Model configuration](https://code.claude.com/docs/en/model-config) · [Use Claude Code in the cloud](https://code.claude.com/docs/en/claude-code-on-the-web) |
| 5 | Each session gets a fresh VM; idle VMs pause and can be reclaimed, so work must be pushed | [Cloud environments](https://code.claude.com/docs/en/cloud-environments) |
| 6 | Network access levels None / Trusted / Full / Custom decide which package registries and domains a session can reach | [Cloud environments — access levels](https://code.claude.com/docs/en/cloud-environments) |
| 7 | Cloud sessions keep running with the client closed; the phone app only monitors and steers them | [Use Claude Code in the cloud](https://code.claude.com/docs/en/claude-code-on-the-web) · [Claude Code on mobile](https://code.claude.com/docs/en/mobile) |
| 8 | GitHub blocks files larger than 100 MiB | [About large files on GitHub](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github) |

## Design system as applied

- **Arc and layers:** fog (1–2) → cloud tops with pink light (3–5) → low open sky (6–8) → high deep blue with a growing contrail (9–13) → stratosphere with stars and the Earth's limb (14–16) → golden sunrise over a sea of clouds (17). All skies are built from gradients, procedural cloud sprites (seeded canvas), stars and light; there are no photos.
- **Colors:** only the 11 brand tokens, as CSS variables in `src/index.html`. Gold is used for one marker per section (shots 2 "ימים", 4 "Claude Code", 10 "שוב ושוב", 16 "בטלפון"), the horizon (Earth-limb arc and sunrise line), and exactly one detail per icon.
- **Type:** Assistant 800/300/600 for Hebrew; Anton + Oswald 200 for the wordmark; IBM Plex Mono 600 for chips, instruments and code. All fonts are self-hosted woff2 files from @fontsource. QA asks Chromium (`CSS.getPlatformFontsForNode`) which fonts actually painted each node, and found no fallback fonts and no italics.
- **Cards:** every headline, NOTAM and visual sits on a white cloud card (36 px radius, 6 px wing-tip corner bottom-left, 2.5 px deep-sky stroke, brand shadow), so contrast holds on the dark layers too.
- **Devices:** a top flight-data strip (boarding strip, WPT n/N, live altimeter 0 → 35,000 FT); a bottom rule with timecode and wordmark; a dashed route with pins and a travelling plane; a phone ↔ control-tower link that pulses once per bar (16:9); NOTAM tags with a sunrise-pink left edge that draws in; 4 cycled grain PNGs; and a vignette.
- **Logo:** the original YUV.AI phoenix from [yuv.ai/logo.png](https://yuv.ai/logo.png), never recolored, shown only on the opening and the end card.
- **Bidi:** Hebrew lines are split into isolated word units. Latin runs are wrapped in `<bdi dir="ltr">`, consecutive Latin words are merged into one unit ("Claude Code", "Opus 5.5"), and comma-separated lists stay as separate units, so "HTML, GSAP, Playwright ו-ffmpeg" reads right-to-left with the ו prefix on the correct side. The arrow ← is an inline SVG, because Assistant has no U+2190.

## Pipeline

```
src/shots.json ─► src/timing.js (formula + beat quantize, shared by page and tools)
               ─► src/index.html + main.js (GSAP paused timeline, window.seek(t, frame), CUES/CUTS)
src/qa.mjs      ─► one still per shot + checks (fonts, overflow, 9:16 safe zone, overlaps, ≥44 px, italics)
src/contact.py  ─► contact sheets + the 3 thumbnails and end-card still the page reuses
src/render.mjs  ─► Playwright Chromium, N workers = CPU cores, CDP PNG capture → ffmpeg chunks → concat
src/audio.py    ─► procedural 108 BPM score (pad, plucks, bass, kick/snare/hats) + SFX from page CUES
src/finalize.py ─► compressor + limiter + 2-pass loudnorm → libx264 slow 5 Mbps + AAC 192k → 720p preview → ffprobe/ebur128 checks
src/evidence.mjs ─► copies the real render loop (between // <evidence> markers) into shot 9
```

Rebuild: `cd src && npm i && pip install numpy scipy pillow && ./build.sh` (`FORMATS=A ./build.sh` for one format).
The PROOF shot needs two passes: the first final render writes `src/gen/stats.json` (`finalize.py A --stats`), and the next render shows it.

## Deviations from the prompt (and why)

- **Music:** the ElevenLabs connector in this session has no credits/subscription endpoint, so credits couldn't be checked. I used the procedural numpy/scipy fallback the prompt allows. It's deterministic, exactly 108 BPM, the same length as the video to the frame, and ends on a hit at the last downbeat.
- **Shot 6 chip:** "network access · setup script" instead of "network policy · setup script", to match the setting names in the docs.
- **Extra chips, all real:** "GitHub App" (shot 5), "git push" (11), "network access: Trusted" (12), "DRAFT PR" and "MP4 · 30 fps" (14).
- **9:16 chrome:** the boarding strip appears only in the opening shot, not in the top strip, because the 44 px minimum doesn't fit three items in 860 px.
- **End card:** the bottom chrome fades out, because white text on the sea of clouds would be unreadable. The wordmark is on the card itself.
- **9:16 duration:** the beat math gives 57.222 s; whole frames give 1717 frames = 57.233 s, which is what's delivered (the 16:9 cut is exactly 2150 frames = 71.667 s).
- **Render loop:** it uses CDP `Page.captureScreenshot` (fast PNG, still lossless) instead of `page.screenshot`. That made rendering about 4× faster, and shot 9 shows this real loop.
"""
(ROOT / 'README.md').write_text(md)
print('README.md written')
